service: express-lambda-ts

# frameworkVersion: '>=3.0.0 <4.0.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1  # (Change region if needed)

functions:
  app:
    handler: src/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - 'dist/**'
    - 'src/**'
    - 'serverless.yml'
