# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: abhay21
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: express-lambda-ts
service: all-functions-in-one

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1  # (Change region if needed)

functions:
  app:
    handler: src/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - 'dist/**'
    - 'src/**'
    - 'serverless.yml'
